spring:
  application:
    name: ugc-sdk-server
  threads:
    virtual:
      enabled: true

logging:
  file:
    path: ./logs
  level:
    root: INFO
    # web 请求与响应日志
    org.springframework.web: INFO

server:
  port: 1696
  address: 0.0.0.0

app:
  game-file-version: 1
  head-magic-number-hex: 0x326
  tail-magic-number-hex: 0x679
